image: docker:stable
#services: 
#  - docker:dind

before_script:
  - apk update && apk add git
  - git config --global user.name "${GITLAB_USER_NAME}"
  - git config --global user.email "${GITLAB_USER_NAME}"

variables:
  CI_REPOSITORY_URL: https://gitlab.com/testgroup625/test_assignment.git
  REGISTRY: registry.gitlab.com
  GROUP: testgroup625
  PROJECT: test_assignment
  TAG: latest

build:
  variables:
    GIT_STRATEGY: empty
  stage: build
  script:
    - docker build -t $REGISTRY/$TAG/$PROJECT:$TAG .

deploy:  
  variables:
    GIT_STRATEGY: empty
  stage: deploy
  script:
    - docker login $REGISTRY -u $GITLAB_USER_NAME -p $GITLAB_PASSWORD
    - docker push $REGISTRY/$GROUP/$PROJECT:$TAG
  only:
  - tags
  
create_k8_deployment:
  script:
    - git checkout master
    - "sed -i \"s|image: |image: \\\"$REGISTRY/$TAG/$PROJECT:$TAG\\\"|g\" deployment.yaml"
    - cat deployment.yaml
    #- "sed \"s|image: \"\"|image: \"$REGISTRY/$TAG/$PROJECT:$TAG\"|g\" deployment.yaml" - working!!!
        #- git remote set-url origin https://$GITLAB_USER_NAME:$CI_GIT_TOKEN@$CI_REPOSITORY_URL#*@
    - git add --all
    - git commit -m "GitLab Runner Push"
    - git status
    - git push --force origin master
