image: docker:19.03.13

variables:
  CI_REPOSITORY_URL: https://gitlab.com/testgroup625/test_assignment.git
  REGISTRY: registry.gitlab.com
  GROUP: testgroup625
  PROJECT: test_assignment
  TAG: latest

build:
  stage: build
  script:
    - docker build -t $REGISTRY/$TAG/$PROJECT:$TAG .

deploy:
  stage: deploy
  script:
    - docker login $REGISTRY -u $GITLAB_USER_NAME -p $GITLAB_PASSWORD
    - docker push $REGISTRY/$GROUP/$PROJECT:$TAG
  only:
  - tags
  
create_k8_deployment:
  before_script:
    - apk update && apk add git
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_NAME}"
  script:
    - git add --all
    - git commit -m "GitLab Runner Push"
    - git push "https://${GITLAB_USER_NAME}:${CI_GIT_TOKEN}@${CI_REPOSITORY_URL#*@}" HEAD:master
