apiVersion: apps/v1
kind: Deployment
metadata:
  name: staistics-deployment
  labels:
    app: statistics_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics_app
  template:
    metadata:
      labels:
        app: statistics_app
    spec:
      containers:
      - name: statistics
        image: ""
#        ports:
#        - containerPort: 80
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: statistics
#spec:
#  selector:
#  app: statistics_app
#  ports:
#    - protocol: TCP
#      port: 8080
#      targetPort: 8080
#      name: statistics-web
